# Generated by Django 5.2.6 on 2025-10-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('km', models.PositiveIntegerField()),
                ('autonomia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ultimaManutencao', models.DateField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_ENTREGA', 'Em Entrega'), ('EM_MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('num_cnh', models.CharField(max_length=14)),
                ('disponivel', models.BooleanField(default=True)),
                ('veiculoAtual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_TRANSITO', 'Em Trânsito'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('data_inicio_prevista', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='app.coordenada')),
                ('origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origens', to='app.coordenada')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataAbastecimento', models.DateField()),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.veiculo')),
            ],
        ),
    ]
