# Generated by Django 5.2.6 on 2025-09-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('km', models.FloatField()),
                ('autonomia', models.FloatField()),
                ('ultimaManutencao', models.DateField()),
            ],
        ),
    ]
