# Generated by Django 5.2.6 on 2025-10-15 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('num_cnh', models.CharField(max_length=20, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_total_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duracao_estimada_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ROTA', 'Em Rota'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('data_inicio_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_fim_prevista', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='app.perfilmotorista')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_carga', models.CharField(help_text='Ex: 2 caixas de eletrônicos', max_length=255)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso total da carga em Kg', max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=2, help_text='Volume total da carga em metros cúbicos (m³)', max_digits=10)),
                ('fragil', models.BooleanField(default=False, verbose_name='Carga Frágil?')),
                ('nome_destinatario', models.CharField(max_length=100)),
                ('telefone_destinatario', models.CharField(max_length=20)),
                ('observacoes_entrega', models.TextField(blank=True, help_text='Ex: Deixar na portaria, cuidado ao manusear.')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_SEPARACAO', 'Em Separação'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('PROBLEMA', 'Problema')], default='PENDENTE', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateTimeField()),
                ('data_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='app.coordenada')),
                ('origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origens', to='app.coordenada')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilcliente')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='app.rota')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('km', models.PositiveIntegerField()),
                ('autonomia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ultimaManutencao', models.DateField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_ENTREGA', 'Em Entrega'), ('EM_MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=15)),
                ('localizacao_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coordenada')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='app.veiculo'),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilmotorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataAbastecimento', models.DateField()),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilmotorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.veiculo')),
            ],
        ),
    ]
