# Generated by Django 5.2.6 on 2025-10-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilmotorista'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_fim_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilmotorista'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.perfilmotorista'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('PROBLEMA', 'Problema')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
    ]
