# Generated by Django 5.2.6 on 2025-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='trajeto_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
