# Generated by Django 5.2.6 on 2025-10-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrega',
            old_name='data_fim_prevista',
            new_name='data_entrega_prevista',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='data_fim_real',
            new_name='data_entrega_real',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='data_inicio_prevista',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='data_inicio_real',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='perfilmotorista',
            name='veiculoAtual',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='localizacao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coordenada'),
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ROTA', 'Em Rota'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_prevista', models.DateTimeField()),
                ('data_fim_prevista', models.DateTimeField()),
                ('data_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('data_fim_real', models.DateTimeField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='app.perfilmotorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas', to='app.veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='app.rota'),
        ),
    ]
