# Generated by Django 5.2.6 on 2025-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_data_fim_prevista_entrega_data_entrega_prevista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='data_fim_real',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='data_inicio_real',
        ),
        migrations.AddField(
            model_name='rota',
            name='distancia_total_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='duracao_estimada_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='data_fim_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='data_inicio_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
