# Generated by Django 5.2.6 on 2025-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abastecimento_motorista_entrega_data_fim_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATRIBUIDA', 'Atribuída'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('PROBLEMA', 'Problema')], default='PENDENTE', max_length=20),
        ),
    ]
