# Generated by Django 5.2.6 on 2025-10-17 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rota_trajeto_polyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=255)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app.entrega')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.coordenada')),
            ],
            options={
                'ordering': ['-data_evento'],
            },
        ),
    ]
