# Generated by Django 5.2.6 on 2025-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_historicoentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='endereco_completo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coordenada',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
