# Generated by Django 5.2.6 on 2025-10-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_entrega_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_SEPARACAO', 'Em Separação'), ('EM_ROTA', 'Em Rota'), ('ENTREGUE', 'Entregue'), ('PROBLEMA', 'Problema')], default='PENDENTE', max_length=20),
        ),
    ]
