# Generated by Django 5.1.1 on 2025-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coordenada_abastecimento_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='motorista',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='autonomia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
