# Generated by Django 5.2.6 on 2025-10-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coordenada_bairro_coordenada_cep_coordenada_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='data_fim_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
