# Generated by Django 5.2.6 on 2025-10-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rota_data_fim_real_rota_data_inicio_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='data_criacao',
            field=models.DateTimeField(null=True),
        ),
    ]
