# Generated by Django 5.2.6 on 2025-10-18 00:46

from django.db import migrations
from django.utils import timezone

def preencher_data_criacao(apps, schema_editor):
    Rota = apps.get_model('app', 'Rota')
    agora = timezone.now()

    Rota.objects.filter(data_criacao__isnull=True).update(data_criacao=agora)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rota_data_criacao'),
    ]

    operations = [
        migrations.RunPython(preencher_data_criacao)
    ]
