# Generated by Django 5.2.6 on 2025-10-18 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20251017_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
