# Generated by Django 5.2.6 on 2025-10-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_rota_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='data_entrega_prevista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
