# Generated by Django 5.2.6 on 2025-10-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_entrega_data_entrega_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
