# Generated by Django 5.2.6 on 2025-10-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_entrega_volume_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
