# Generated by Django 5.2.6 on 2025-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_manutencao_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='km_ultima_manutencao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
